name: Pull Request Text Generator Workflow

on:
  pull_request:
    types: [opened, edited, reopened]
  issue_comment:
    types: [created]

jobs:
  generate-pr-text:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run for PR
        if: github.event_name == 'pull_request'
        uses: ./
        with:
          openai_api_key: ${{ secrets.OPENAI_API_KEY }}
          instruction: ${{ github.event.pull_request.body }}
      - name: Run for comment
        if: github.event_name == 'issue_comment' && github.event.issue.pull_request
        uses: ./
        with:
          openai_api_key: ${{ secrets.OPENAI_API_KEY }}
          instruction: ${{ github.event.comment.body }}
