name: Pull Request Text Generator Workflow

on:
  pull_request:
    types: [opened, edited, reopened]
  issue_comment:
    types: [created]

jobs:
  generate-pr-text:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run for PR
        if: github.event_name == 'pull_request'
        uses: ./
        with:
          openai_api_key: ${{ secrets.OPENAI_API_KEY }}
          openai_base_url: https://api.fireworks.ai/inference/v1
          generation_model: accounts/fireworks/models/mixtral-8x7b-instruct
          user_prompt: ${{ github.event.pull_request.body }}
      - name: Debug PR Number
        if: github.event_name == 'issue_comment' && github.event.issue.pull_request
        run: echo ${{ github.event.issue.number }}
      - name: Fetch PR details for comment event
        if: github.event_name == 'issue_comment' && github.event.issue.pull_request
        id: pr_details
        uses: octokit/request-action@v2.x
        with:
          route: GET /repos/${{ github.repository }}/pulls/${{ github.event.issue.number }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Run for comment
        if: github.event_name == 'issue_comment' && github.event.issue.pull_request
        uses: ./
        with:
          openai_api_key: ${{ secrets.OPENAI_API_KEY }}
          openai_base_url: https://api.fireworks.ai/inference/v1
          user_prompt: ${{ github.event.comment.body }}
          target_branch: ${{ fromJson(steps.pr_details.outputs.data).base.ref }}
          source_branch: ${{ fromJson(steps.pr_details.outputs.data).head.ref }}
          pull_request_number: ${{ github.event.issue.number }}
          generation_model: accounts/fireworks/models/mixtral-8x7b-instruct
