name: Pull Request Text Generator Workflow

on:
  pull_request:
    types: [opened, edited, reopened]
  issue_comment:
    types: [created]

jobs:
  generate-pr-text:
    runs-on: ubuntu-latest
    outputs:
      pr_text: ${{ steps.set_multiline_output.outputs.formatted_output }}
      comment_pr_text: ${{ steps.auto_pr_writer_for_comment.outputs.generated_pr_text }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run for PR
        if: github.event_name == 'pull_request'
        id: auto_pr_writer_for_pr
        uses: ./
        with:
          openai_api_key: ${{ secrets.OPENAI_API_KEY }}
          openai_base_url: https://api.fireworks.ai/inference/v1
          generation_model: accounts/fireworks/models/mixtral-8x7b-instruct
          user_prompt: ${{ github.event.pull_request.body }}

      - name: Set Multiline Output
        if: github.event_name == 'pull_request'
        id: set_multiline_output
        uses: actions/github-script@v5
        with:
          script: |
            const output = `${{ steps.auto_pr_writer_for_pr.outputs.generated_pr_text }}`;
            core.setOutput('formatted_output', output);

      - name: Run for comment
        if: github.event_name == 'issue_comment' && github.event.issue.pull_request
        id: auto_pr_writer_for_comment
        uses: ./
        with:
          openai_api_key: ${{ secrets.OPENAI_API_KEY }}
          openai_base_url: https://api.fireworks.ai/inference/v1
          user_prompt: ${{ github.event.comment.body }}
          target_branch: ${{ github.event.pull_request.base.ref }}
          source_branch: ${{ github.event.pull_request.head.ref }}
          pull_request_number: ${{ github.event.issue.number }}
          generation_model: accounts/fireworks/models/mixtral-8x7b-instruct

  update-pr-description:
    runs-on: ubuntu-latest
    needs: generate-pr-text
    steps:
      - name: Update PR description from PR
        if: github.event_name == 'pull_request'
        uses: riskledger/update-pr-description@v2
        with:
          body: ${{ needs.generate-pr-text.outputs.pr_text }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update PR description from Comment
        if: github.event_name == 'issue_comment' && github.event.issue.pull_request
        uses: riskledger/update-pr-description@v2
        with:
          body: ${{ needs.generate-pr-text.outputs.comment_pr_text }}
          token: ${{ secrets.GITHUB_TOKEN }}
